version: '3.8'

services:
  app:
    build:
      context: .  # U¿ywa pliku Dockerfile w bie¿¹cym katalogu
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=mssql-server
      - DB_PORT=1433
      - DB_NAME=your_database_name
      - DB_USER=sa
      - DB_PASSWORD=yourStrongPassword123
    depends_on:
      - mssql-server

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge
