version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=mssql-server
      - DB_PORT=1433
      - DB_NAME=your_database_name
      - DB_USER=sa
      - DB_PASSWORD=yourStrongPassword123
    network_mode: host

  mssql-server:
    build:
       context: .
       dockerfile: Dockerfile.mssql
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword123
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/init.sql
    command: /bin/bash -c " /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P yourStrongPassword123 -d master -i /init.sql"
    network_mode: bridge

volumes:
  mssql-data:

