version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=mssql-server
      - DB_PORT=1433
      - DB_NAME=your_database_name
      - DB_USER=sa
      - DB_PASSWORD=yourStrongPassword123
    network_mode: host

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    network_mode: host

volumes:
  mssql-data:

