CREATE DATABASE your_database_name;
GO

USE your_database_name;
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FOREIGN KEY(PId) REFERENCES UserProgress(Id)
    Username NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL
);
GO